### ISSUE TITLE
Speed up ModelViewTransform2.modelToViewX/Y

### ISSUE THREAD

**Issue by samreid** [phetsims/phetcommon#12]
I currently have ModelViewTransform2.modelToViewX/Y in an inner loop in Energy Skate Park: Basics (when dragging the track).  I have plans to optimize this a different way in the future, but it seems like there is a straightforward way to optimize those functions.

They are currently written as:

```javascript
    modelToViewX:        function( x )      { return this.transformPosition2( new Vector2( x, 0 ) ).x; },
    modelToViewY:        function( y )      { return this.transformPosition2( new Vector2( 0, y ) ).y; },
```

But I think this is equivalent (with many fewer allocations):

```javascript
    modelToViewX:        function( x )      { return this.matrix.m00() * x + this.matrix.m02(); },
    modelToViewY:        function( y )      { return this.matrix.m11() * y + this.matrix.m12(); },
```

The former is more readable, but we may wish to use the latter for performance/gc reasons, and just to document the math.

**Comment by pixelzoom** [comment]
Looks like we're still discussing optimization of `modelToViewDeltaX, modelToViewDeltaY, viewToModelDeltaX, viewToModelDeltaY`.  Looking into the implementation of these, the only thing we'll save is a function call.  Do we think that's significant for animation loop or dragging? We would be losing the argument validation currently provided by the Transform3 functions.

If so... The implementations would be:

```js
modelToViewDeltaX: function( x ) { return this.matrix.m00() * x; },
modelToViewDeltaY: function( y ) { return this.matrix.m11() * y + this.matrix.m12(); },
viewToModelDeltaX: function( x ) { return this.getInverse().m00() * x; },
viewToModelDeltaY: function( y ) { return this.getInverse().m11() * y; },
```

**Comment by samreid** [comment]
Isn't the getInverse in viewToModelDelta expensive?  I suspect it is.

**Comment by pixelzoom** [comment]
@jonathanolson changed the implementation of viewToModelX and viewToModelX in effdd0c, and he used `getInverse`, so I was mimicking that pattern. Perhaps he changed for a different reason, and wasn't addressing this issue?

**Comment by pixelzoom** [comment]
Seems like calling `getInverse` twice in viewToModelX and viewToModelY is wasteful, and should be changed.  But in general, I don't see a more efficient option to calling getInverse.

**Comment by samreid** [comment]
> But in general, I don't see a more efficient option to calling getInverse.

We don't need to invert the entire matrix in order to do a single computation with its inverse.  We just need the power of maths.

**Comment by samreid** [comment]
It looks like @jonathanolson optimized the transform calls in dot https://github.com/phetsims/dot/commit/340626a2e390fe3652ce06a73e6610a7763726fa on Sept 18 (2 days after this issue was born).

**Comment by pixelzoom** [comment]
Looking into the implementation of getInverse, it incurs a cost only if the inverse is invalid. So 2 calls to getInverse in the same function is currently no different than 1 call (except for the cost of the function call itself).  But that relies on knowledge of the implementation, so I still changed viewToModelX and viewToModelY to call getInverse once each.

**Comment by pixelzoom** [comment]
So what else should we do here?...

**Comment by samreid** [comment]
In my opinion, work on issues like this one should be deferred until if/when we have an application where this issue demonstrably a performance bottleneck.  My recommendation would be to close it.  We can reopen it if it ever appears in a profiler.

**Comment by pixelzoom** [comment]
Closing.
