### ISSUE TITLE
Bucket options awkward

### ISSUE THREAD

**Issue by samreid** [phetsims/phetcommon#14]
In Bucket.js, options are required: if you don't pass options then you get runtime exception from this line:

```
position: options.position || Vector2.ZERO,
```

Also, the way options.width and height are converted to size field is awkward:

```
size: new Dimension2( options.width || 200, options.height || 50 ),
```

Why not just provide a default size?

**Comment by pixelzoom** [comment]
Default value for position option was clearly brain damaged, so changed to:

`position: Vector2.ZERO,`

options.width and options.height were unused by clients of Bucket or its subtype SphereBucket, so changed to:

`size: new Dimension2( 200,  50 ),`
