### ISSUE TITLE
Need a common "Fraction" class

### ISSUE THREAD

**Issue by jbphet** [phetsims/phetcommon#19]
I just copied Fraction.js from Graphing Lines into Area Builder and made some mods.  I noticed there is also a version in Fraction Matcher.  All are pretty simple, and we should make a common version and put it here.

**Comment by pixelzoom** [comment]
gcd was moved to dot.Util awhile ago (unfortunately the commit was not tagged here.)

Looks like the only thing left to do is to remove Fraction.fraction and its 206 usages.

**Comment by pixelzoom** [comment]
All work completed, closing. Feel free to review, if anyone is so inclined.
