### ISSUE TITLE
add visibility annotations

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phetcommon#25]
Add a @public, @protected or @private annotation to anything that's publicly visible.
See https://github.com/phetsims/tasks/issues/307.

**Comment by pixelzoom** [comment]
@jbphet The remaining files requiring annotations are Bucket.js, Fraction.js and SphereBucket.js, all of which I believe were created by you. Would you mind taking care of those?

**Comment by samreid** [comment]
Earlier we assigned this issue to me.  I'll take a look at those files and defer to @jbphet if I can't infer.

**Comment by samreid** [comment]
Well, I did Bucket.js, but am going to recommend that @jbphet do SphereBucket.

**Comment by samreid** [comment]
Fraction also complete.  @jbphet can you look at SphereBucket.js?

**Comment by jbphet** [comment]
Okay, I did SphereBucket and also cleaned it up quite a bit to look more like our current coding style and standards.  I believe our work here is done.  Closing.
