### ISSUE TITLE
toCamelCase is duplicated

### ISSUE THREAD

**Issue by samreid** [phetsims/phetcommon#30]
PhET implements toCamelCase in the following locations:

chipper/eslint/rules/string-require-statement-match.js
chipper/js/common/ChipperStringUtils.js
phetcommon/js/util/StringUtils.js
together/js/SimWrapperUtils.js

Are all of these necessary?  Can some of them be deleted?

**Comment by pixelzoom** [comment]
toCamelCase has now been copied to yet-another repo, phet-io-wrappers.

**Comment by pixelzoom** [comment]
As of 12/29/18, we're now up to 6 copies of `toCamelCase`, 3 of which are related to PhET-iO:

chipper/eslint/rules/string-require-statement-match.js
perennial/grunt/createSim.js
phetcore/js/toCamelCase.js
phet-io-wrapper-sonification/lib/WrapperUtils.js
phet-io-wrappers/common/js/Client.js
tandem/js/Tandem.js

Assigning to @ariel-phet to prioritize and assign.

**Comment by samreid** [comment]
I've also noticed that the implementations are not all the same.

**Comment by ariel-phet** [comment]
Seems like a good iO meeting discussion (and how big of task is it to reduce these to one)

**Comment by pixelzoom** [comment]
This came up again in https://github.com/phetsims/phet-io-wrappers/issues/218, review of PhET-iO API.

**Comment by chrisklus** [comment]
https://github.com/phetsims/phet-core/issues/72 is assigned to me to eliminate these duplications. Closing
