### ISSUE TITLE
branch: hewlett-*

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/phetcommon#31]
Tracking branches for https://github.com/phetsims/yotta/issues/17 and https://github.com/phetsims/phetcommon/issues/28.

The branches/commits update the Hewlett Google Analytics property, and are used for maintenance releases.

Discuss with me before considering removal of the branches!

**Comment by pixelzoom** [comment]
@jonathanolson I see no hewlett-* branches in phetcommon.  Presumably they have been deleted.  OK to close this issue?

**Comment by jonathanolson** [comment]
Looks like it, thanks!
