### ISSUE TITLE
new approach to placeholders in translated strings

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phetcommon#36]
We're currently using Java's MessageFormat syntax for filling in placeholders in translated strings (e.g. `"{0} for {1}?"`). We did this because it was easy to implement (see `StringUtils.format`) and made it easy to port Java code and strings.

In a Skype discussion about such strings, we identified a few issues with this approach:

1. It's difficult for translators to determine the semantics of the placeholders. We've attempted (inconsistently) to do that via string key names (e.g. "pattern.0items.for.1cost").  Longterm would be to add metadata that describes the placeholders, and present that metadata to translators in Rosetta. But that's unlikely to happen in the near future.

2. The semantics of placeholders may similarly be unclear to developers. And when calling StringUtils.format, you'd better have the placeholders in the correct order.

@jonathanolson suggested a new approach, @samreid and I gave additional input. The new approach:

Instead of numeric placeholders, use named placeholders, with names chosen to describe the placeholder's semantics. Placeholders would be delimited with double curly braces (`"{{units}}"`), as is done in simula-rasa and other templates. E.g. in a string file:

```js
  "itemsForCost": {
    "{{numberOfItems}} for ${{cost}}?"
  },
```

At call sites, the placeholder values would be specified via a hash whose keys match the placeholder names. E.g.:

```js
var itemsForCostString = require( 'string!../itemsForCost' );
...
// 'Apples of $10?'
var myString = StringUtils.fillIn( itemsForCostString, {
  numberOfItems: 'Apples',
  cost: 10
} );
```

Questions:
• There's no info about the type of the placeholders in this approach, is that OK?
• Rosetta will need to validate the translated string, to make sure that it contains all of the same placeholders as the English string. What would it take to do that?
• Would we deprecate `StringUtils.format`?
• Would we replace strings that use the old format? That would involve changing English and translated strings, and probably string keys.
• What to name the new formatting function? (I called it `StringUtils.fillIn` in the example above.)

**Comment by pixelzoom** [comment]
While we're at it... It sure would be nice if `stringTest=double` treated placeholders correctly.  Imo, it should ignore (preserve) the placeholders, and double the non-placeholder parts of the string. 

E.g., for string `"{0} for {1}?"`
current behavior: `"{0} for {1}?:{0} for {1}?"`
desired behavior: `"{0} for:for {1}?:?"`

If the new implementation does validation of the values hash (verifies that each field in the hash has a corresponding placeholder in the string), then we may also need to change `stringTest=long`, since it currently wipes out placeholders entirely.

**Comment by pixelzoom** [comment]
2/23/17 consensus:

• Like this approach
• Use going forward
• Don't deprecate `StringUtils.format`, but don't use it in new code
• Don't change any existing strings
• Validation will check that all placeholders have a corresponding key in value cache. Extra keys OK.
• Don't address stringTest at the same time as this, separate issue.

**Comment by pixelzoom** [comment]
I'll do this, low priority. Check in with others about function name, but `StringUtils.fillIn` seemed to be acceptable to everyone at dev meeting.

**Comment by pixelzoom** [comment]
Note to self: Will need to address embedding marks (eg LTR, RTL) as was done for `StringUtils.format`. Hopefully I can look at `StringUtils.format` for guidance.

**Comment by pixelzoom** [comment]
Skype discussion:

[4/11/17, 4:12:35 PM] Chris Malley: Does anyone have regex (or other) chops for pulling all of the placeholders out of a template? For example:  "{{name}} is {{age}} years old" -> [ "name", "age" ]
[4/11/17, 4:13:25 PM] Jonathan Olson: checking
[4/11/17, 4:14:23 PM] Jonathan Olson: '{{name}} is {{age}} years old'.match( /\{\{[^\{\}]+\}\}/g )
[4/11/17, 4:14:27 PM] Jonathan Olson: returns ["{{name}}", "{{age}}"]
[4/11/17, 4:14:59 PM] Chris Malley: That'll work. I can use those as the tokens to replace. And delete the brackets to lookup the values in the hash.
[4/11/17, 4:15:07 PM] Jonathan Olson: ok
[4/11/17, 4:15:14 PM] Chris Malley: thanks!
[4/11/17, 4:15:16 PM] Jonathan Olson: no problem
[4/11/17, 4:15:30 PM] Jonathan Olson: check its behavior in 1-match and 0-match cases though
[4/11/17, 4:15:57 PM] Jonathan Olson: (0-match case returns null, NOT an array)
[4/11/17, 4:16:30 PM] Chris Malley: yep. 1-match is fine.

**Comment by pixelzoom** [comment]
This feature is now implemented, along with unit tests in phetcommon/tests/qunit/.

@jonathanolson would you mind reviewing, since you've done quite a bit of work in StringUtils in the past?

**Comment by pixelzoom** [comment]
Labeling for developer meeting, to notify developers that `StringUtils.fillIn` is ready (pending review), and should be used going forward instead of `StringUtils.format`.

**Comment by jonathanolson** [comment]
Looks good. Made a few minor tweaks in commit above, feel free to review.

I'll add in phetcommon unit tests into continuous testing.

**Comment by pixelzoom** [comment]
Labeling for developer meeting, to notify developers that StringUtils.fillIn is ready (pending review), and should be used going forward instead of StringUtils.format.

**Comment by samreid** [comment]
My forthcoming thumbs-up indicates I understand to use `fillIn` for future code.

**Comment by jonathanolson** [comment]
Already replaced the one format usage in Proportion Playground.

**Comment by pixelzoom** [comment]
Reviewed at developer meeting. Closing.
