### ISSUE TITLE
Yotta messages should track brand directly.

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/phetcommon#37]
Give SHA to build-an-atom (@samreid  and @jbphet) to cherry-pick.

Presumably this will increment the pingver.

**Comment by jonathanolson** [comment]
Added and tested briefly above. Can you cherry-pick into a relevant phetcommon branch for build-an-atom's RC, build, and ensure that the request to immediate.gif has 'brand=phet-io'?

**Comment by jonathanolson** [comment]
SHA is 49b5cb0d6befc50e516598e52f4c90cb1f8be963, so:
```sh
git cherry-pick 49b5cb0d6befc50e516598e52f4c90cb1f8be963
```

**Comment by jonathanolson** [comment]
Will handle on server-side in my working copy changes. My comment `// Only one protocol version is currently supported` will never see the light of day!

**Comment by jonathanolson** [comment]
Code to back-fill the brand server-side:
```js
if ( protocolVersion === 2 ) {
  yottaInfo.brand = ( yottaInfo.version.indexOf( '-phetio' ) >= 0 ) ? 'phet-io' : 'phet';
}
```

**Comment by jbphet** [comment]
This SHA was incorporated into the Build an Atom 1.4 branch, and should now be live on the published version v1.4.0, see https://github.com/phetsims/build-an-atom/commit/6c084a756f8ee992e2b7b6addb049e7a3e532f6b.  @jonathanolson - can you verify that this is working as expected?

**Comment by samreid** [comment]
It sounds like @jbphet and @jonathanolson are on the case, I'll unassign myself.

**Comment by jonathanolson** [comment]
> @jonathanolson - can you verify that this is working as expected?

Build an Atom production is 1.2 (although there is a 1.4-phetio branch), and for some reason this doesn't seem to be live on the latest version of Build an Atom. Investigating.

**Comment by jonathanolson** [comment]
I'm also very confused. https://phet-io.colorado.edu/sims/beers-law-lab/1.4.0-phetio/beers-law-lab_en-phetio.html (the only 1.4 version I could find on the phet-io website) doesn't event send Yotta messages, much less include the brand with them.

**Comment by jonathanolson** [comment]
Found the right link in phet-io, confirmed that it is sending the brand.
