### ISSUE TITLE
phetcommon units tests broken by PhET-iO

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phetcommon#39]
Discovered while adding unit tests for https://github.com/phetsims/phetcommon/issues/36.

Running http://localhost/~cmalley/GitHub/phetcommon/tests/qunit/, I get:

> Uncaught Error: Script error for: text
http://requirejs.org/docs/errors.html#scripterror
    at makeError (require-2.1.11.js:166)
    at HTMLScriptElement.onScriptError (
> Uncaught Error: Script error for: ifphetio
http://requirejs.org/docs/errors.html#scripterror
    at makeError (require-2.1.11.js:166)
    at HTMLScriptElement.onScriptError (require-2.1.11.js:1681)

**Comment by pixelzoom** [comment]
Looks like TANDEM needs to be defined in config.js.

**Comment by pixelzoom** [comment]
Looks like `text` and `phetio` plugins are missing from config.js.

**Comment by pixelzoom** [comment]
... and TANDEM needs to be defined in config.js.

**Comment by pixelzoom** [comment]
... and REPOSITORY needs to be defined in config.js.

**Comment by pixelzoom** [comment]
config.js fixed in above commit.

Assigning this to @jbphet to review, since he broke things when instrumenting Build An Atom in https://github.com/phetsims/phetcommon/commit/d128c5fb2ffcdafe82bb8b26096cff3790ddf872.

**Comment by pixelzoom** [comment]
Labeling for developer meeting, to notify developers that `StringUtils.fillIn` is ready (pending review), and should be used going forward instead of `StringUtils.format`.

**Comment by jbphet** [comment]
The fix looks reasonable to me.  Two questions:

1. Why does the addition of phet-io support in https://github.com/phetsims/phetcommon/commit/d128c5fb2ffcdafe82bb8b26096cff3790ddf872 cause a need for REPOSITORY to be defined in config.js?
2. Why does that same commit cause a need for the text plugin?

**Comment by pixelzoom** [comment]
No idea. I'm not familiar with how the unit tests are put together.

**Comment by pixelzoom** [comment]
Unit tests are still working and no one has answered the questions in https://github.com/phetsims/phetcommon/issues/39#issuecomment-293685855 in 4+ months. So closing.
