### ISSUE TITLE
StringUtils.fillIn throws assertion when value is 0

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/phetcommon#40]
```js
        assert && assert( values[ key ], 'missing value for ' + key );
```

This will assert out when ```values[ key ]``` is 0.

**Comment by jessegreenberg** [comment]
@pixelzoom can you please review?

**Comment by pixelzoom** [comment]
I'm not clear on what's going on here. The keys to `fillIn` are supposed to be strings. Why do we need to support 0 (a number)? And if 0, why not other numbers?

**Comment by pixelzoom** [comment]
If `var key` is indeed being coerced to a number, then the correct fix to this is ensure that it remains a string.  I.e.:

```js
var key = '' + placeholder.replace( '{{', '' ).replace( '}}', '' );
```

**Comment by pixelzoom** [comment]
Or better yet, ensure that key does not represent a number.  We should not be using numbers placeholders, e.g. `{{0}}`.

**Comment by jessegreenberg** [comment]
Keys should be strings, but the assertion didn't like the falsy 0 value. The documentation has this example:

 ```
StringUtils.fillIn( '{{name}} is {{age}} years old', { name: 'Fred', age: 23 } )
```

Without something like https://github.com/phetsims/phetcommon/commit/4576be484111b74bc4ddbe313844e9a4952f1440, ```fillIn``` will throw an assertion for
```
StringUtils.fillIn( '{{name}} is {{age}} years old', { name: 'Fred', age: 0 } )
```

**Comment by pixelzoom** [comment]
Ah, I see..    The correct assertion is then:

```js
assert && assert( values[ key ] !== undefined, 'missing value for ' + key );
``

Fixed in above commit. @jessegreenberg please review.

**Comment by pixelzoom** [comment]
I also fixed the assertion message:

```js
assert && assert( values[ key ] !== undefined, 'missing key ' + key );
```

This now supports all falsy values except `undefined`.

**Comment by jessegreenberg** [comment]
Works great, thanks!
