### ISSUE TITLE
Fraction: implementation of isLessThan seems unnecessarily complicated

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phetcommon#43]
@jonathanolson added this to `Fraction`:

```js
    /**
     * Returns whether this fraction has a value that is less than the provided fraction.
     * @public
     *
     * @param {Fraction} fraction
     * @returns {boolean}
     */
    isLessThan: function( fraction ) {
      assert && assert( fraction instanceof Fraction, 'fraction is not a Fraction: ' + fraction );

      return SCRATCH_FRACTION.set( this ).subtract( fraction ).sign === -1;
    },
...
  // Used to avoid GC - NOTE: Do NOT move in front of the constructor/inherit, as it is creating a copy of the type
  // defined.
  var SCRATCH_FRACTION = new Fraction( 1, 1 );
```

Why can't the above be replaced with this?

```js
    /**
     * Returns whether this fraction has a value that is less than the provided fraction.
     * @public
     *
     * @param {Fraction} fraction
     * @returns {boolean}
     */
    isLessThan: function( fraction ) {
      assert && assert( fraction instanceof Fraction, 'fraction is not a Fraction: ' + fraction );

      return fraction.getValue() < this.getValue();
    },
```

**Comment by jonathanolson** [comment]
I guess I was thinking in a "rational arithmetic" mindset, where usually types like Fraction don't use intermediate floating point comparisons for operations due to loss of precision. Since we are basically guaranteed that JS's numbers work as integers up to Number.MAX_SAFE_INTEGER, I figured that we don't have to worry at all about floating point issues for numerators/denominators up to the square root of that.

**Comment by jonathanolson** [comment]
> Why can't the above be replaced with this?

If you verify it will be exact for that general range of input values, feel free to make the change.

**Comment by pixelzoom** [comment]
Since `getValue` uses division, I can't "verify it will be exact for that general range of input values" without adding additional functions.  So I'm going to do nothing and close.
