### ISSUE TITLE
Fraction: change isInteger to avoid precious issues

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phetcommon#44]
Noted in https://github.com/phetsims/equality-explorer/issues/70.

Fraction `isInteger` currently uses `getValue`, which uses division and therefore may have precious issues:

```js
// @public - Floating-point error is not an issue as long as numerator and denominator are integers < 2^53
getValue: function() {
  return this.numerator / this.denominator;
},

// @public
isInteger: function() {
  return Util.isInteger( this.getValue() );
},
```

Proposed change to `isInteger` is:

```js
isInteger: function() {
  return ( this.numerator % this.denominator === 0 );
},
```

Add unit tests for all combinations of positive and negative numerators and denominators, zero numerator, and zero denominator.

**Comment by pixelzoom** [comment]
Change completed, unit tests added and passing.

@jonathanolson would you mind taking a quick peek, since you and I discussed this on Slack?

**Comment by jonathanolson** [comment]
Looks good to me.
