### ISSUE TITLE
Fraction: verify that numerator and denominator are integers

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phetcommon#45]
There are a number of places in Fraction where `this.numerator` and `this.denominator` are set without verifying that they are integer values.  And I'm hitting such a condition in https://github.com/phetsims/equality-explorer/issues/71.

So I'm going to make a couple of changes:

(1) `{public}` `this.numerator` and `this.denominator` will become `{private}` `this._numerator` and `this._denominator` respectively.

(2) ES5 setters and getters will be added for `numerator` and `denominator`, where the setters verify that the values are integers.  

For clients, this means no API changes.  For Fraction, this means we will always verify that the numerator and denominator are integer values.

**Comment by pixelzoom** [comment]
ES5 set/get pattern implemented in above commit. 

@ariel-phet please assign someone to review.

**Comment by Denz1994** [comment]
The changes look good. The unit tests also seem comprehensive enough for testing. Closing this issue.
