### ISSUE TITLE
Supporting external Google Analytics tracking

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/phetcommon#46]
It's come up where a 3rd party wants to provide a link to a sim, but get Google Analytics data out of it. @kathy-phet requested a feature where a query parameter can be provided to give a custom GA property that we can send data to.

I'll plan on implementing this as `?ga=UA-EXAMPLE` for phet/phet-io brands.

**Comment by jonathanolson** [comment]
@kathy-phet, do we have a tracker that we can test this with?

**Comment by kathy-phet** [comment]
I looked on GA and for the PhET Interactive Simulations Dev account there is this tracker number: 
UA-36363897-1

Does that look like what you need? 
I don't see any reason we cannot test this query parameter with that tracker.

**Comment by jonathanolson** [comment]
Tested and verified things are working nicely. Closing.

**Comment by jonathanolson** [comment]
Reopening so I can track for the maintenance release.

**Comment by jonathanolson** [comment]
Also @kathy-phet so you're aware, the google analytics patches were integrated into the release branches and RCs are ready.

**Comment by jonathanolson** [comment]
@kathy-phet maintenance releases are complete on this (and Molarity/RPAL's recent versions include it also). Feel free to tell people about the `?ga` and ?gaPage` query parameters.

**Comment by kathy-phet** [comment]
Thanks, Jonathan!
