### ISSUE TITLE
Can StringUtils.endsWith be implemented with _.endsWith()?

### ISSUE THREAD

**Issue by samreid** [phetsims/phetcommon#48]
From Slack:

@zepumph said:
> Can anyone think of a reason why StringUtils.endsWith shouldn't just use _.endsWith()?

@chrisklus said:
> isn’t there an es6 endsWith()? (edited) 

@zepumph said:
> Yes but I don't think it exists on ie11, and we don't use babel to polyfill that, just transpile.

@chrisklus said:
> ooh i forgot we don’t polyfill that

@samreid said:
Great idea!  What about taking that idea one step further and deleting StringUtils.endsWith and recommending clients use _.endsWith instead?

**Comment by pixelzoom** [comment]
I will defer to @samreid, since it looks like he created `StringUtils.endsWith` on 7/13/16.  Looks like there are only 5 usages, all in StringUtilsTest, so not in any production code.

**Comment by samreid** [comment]
Great!  Let's remove `StringUtils.endsWith` and advocate for client code to use `_.endsWith` instead.

**Comment by samreid** [comment]
The diff wrapper, interaction dashboard preprocessor, studio and dataStreamTests are using string.endsWith and hence will not work on IE11.  It looks like all of these places can use lodash, so I'll look into that.

**Comment by samreid** [comment]
>  It looks like all of these places can use lodash, so I'll look into that.

It looks like preprocessor does not yet use lodash.

**Comment by samreid** [comment]
OK I replaced suitable cases with _.endsWith and will leave this issue open for dev meeting as a public service announcement to remind others that `_.endsWith` is forbidden for IE.  I added a code review checklist item for it.

**Comment by Denz1994** [comment]
From dev meeting: 08/29/19

@samreid has alerted us of this recent change described in the previous comments. Closing this issue.
