### ISSUE TITLE
SphereBucket fails code review

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phetcommon#52]
Noted while converting to ES6 for https://github.com/phetsims/tasks/issues/1044.

SphereBucket fails PhET code review.  Many methods are missing documentation and `@param` annotations. Since this is common code, it should be documented.

**Comment by jbphet** [comment]
I've added method headers, visibility annotations where they were needed, cleaned up some of the other documentation, and converted several functions to ES6 style.  @pixelzoom - care to have a look?

**Comment by pixelzoom** [comment]
👍🏻 closing
