### ISSUE TITLE
Can SphereBucketIO.toStateObject use ReferenceIO?

### ISSUE THREAD

**Issue by samreid** [phetsims/phetcommon#54]
SphereBucketIO currently looks like so:

```js
  toStateObject: sphereBucket => {
    return { particles: sphereBucket._particles.map( particle => particle.tandem.phetioID ) }; // TODO: https://github.com/phetsims/phet-io/issues/1774 use ReferenceIO?
  },
```

Can SphereBucketIO.toStateObject use ReferenceIO?

**Comment by zepumph** [comment]
How about that?

**Comment by samreid** [comment]
It looks reasonable and consistent with what I did for https://github.com/phetsims/circuit-construction-kit-common/issues/708.  I'll factor out the IO type in an upcoming commit.

**Comment by samreid** [comment]
I factored out the IO type so it isn't created over and over.  I wasn't sure how to test this, but it seems reasonable enough to close.
