### ISSUE TITLE
Bucket and SphereBucket have dependencies on scenery and shred.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phetcommon#55]
I got pretty far along with converting Bucket and SphereBucket to TypeScript.  Then I ran into 2 dependency problems:

(1) They depend on scenery, either `IColor` or `IPaint` depending on how you choose to define options `baseColor` and `captionColor`. 

(2) SphereBucket depends on shred for `Particle`. 

Neither of those dependencies is currently supported by tsconfig files.  And I'm afraid that there may be some circularity. So I bailed.  Assigning to the author @jbphet to address.

**Comment by samreid** [comment]
Converted to TS in the commits. It's OK for phetcommon to depend on scenery and shred for these types.  Closing.
