### ISSUE TITLE
StringUtils.fillIn needs a DerivedProperty implementation

### ISSUE THREAD

**Issue by samreid** [phetsims/phetcommon#56]
From https://github.com/phetsims/axon/issues/408, we would like to add a new StringUtils.fillIn - style method that takes LocalizedStringProperty instances and returns an instrumented DerivedProperty.

Still needs to be compatible with everything in description.

New name for the new method, and mark `fillIn` as deprecated.

Maybe `fillInDynamic` or `dynamicFillIn`?

@pixelzoom suggests `createDerivedStringProperty` or something like that.

@jonathanolson points out it can be a new type, like `new DerivedStringProperty()`.  or `new InterpolatedStringProperty()` or `new PatternStringProperty(pattern, values, options)` or `new TemplateStringProperty()`?

Our current favorite: `new PatternStringProperty(pattern, values, options)`

**Comment by jonathanolson** [comment]
PatternStringProperty was added. @samreid can this be closed?

**Comment by samreid** [comment]
Yes, thanks.  Closing.
