### ISSUE TITLE
Design and maintenance release all HTML sims with new GA4 code

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/phetcommon#57]
We need to eagerly add the GA4 code needed to upgrade to the new google analytics.

**Comment by kathy-phet** [comment]
@jonathanolson - Can you paste the GA code here with the fields and info we currently push to GA? We can think about what to do for this next iteration.

**Comment by kathy-phet** [comment]
JO says this ... https://github.com/phetsims/phetcommon/blob/6c6d4186db1d5b0fa99a73c3f522499873bdafb0/js/analytics/google-analytics.js#L141 - main tracker ID in our codebase

**Comment by jonathanolson** [comment]
I believe this was handled.
