### ISSUE TITLE
Test Google Tag Manager

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/phetcommon#59]
@mattpen @jonathanolson here is the code to install Tag Manager (currently, it only fires our GA4 base tag on every page)

Install Google Tag Manager
Copy the code below and paste it onto every page of your website.
Paste this code as high in the <head> of the page as possible:
```
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-WLNGBXD');</script>
<!-- End Google Tag Manager -->
```
Additionally, paste this code immediately after the opening <body> tag:
```
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-WLNGBXD"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
```
For more information about installing the Google Tag Manager snippet, visit our [Quick Start Guide ](https://developers.google.com/tag-manager/quickstart).

I suppose we'll add this to (1) ox-dev and (2) a sim to test default GA4 collection. Then, explore capturing more custom data?

**Comment by mattpen** [comment]
@oliver-phet - I've put the code snippets in place on ox-dev, but I'm not sure how to check that out on the analytics side.

**Comment by mattpen** [comment]
I'm not seeing a lot of indication that GTM is any better for our usage than the Global site tag (gtag.js), as we are only using the one tracker.  I also don't think it gives us any capability to track behaviors in Google Analytics without defining Events.

Articles I reviewed:
https://support.google.com/tagmanager/answer/7582054?hl=en
https://measureschool.com/google-tag-manager-vs-global-site-tag/

I looked around at the GTM for our tag, and it looks like it only automatically collects the same data that the gtag.js is collecting, e.g. file_downloads (if the links are setup correctly), form interactions, etc.  So if we want to track things like preferences dialog interactions or donate dialog interactions, we'll still need to write and deploy code.  It looks like the two (GTM and gtag.js) are fairly equivalent for our usage.

**Comment by oliver-phet** [comment]
I'll need to do a bit more reading, on the capabilities of GTM regarding code-less event tracking. I definitely got the impression that was possible from the LinkedIn learning intro course, but perhaps it just allows _changes_ to the ways existing custom events are tracked without editing the source code.

One potential benefit of using GTM that I see: we could activate both the GA4 tag and UA tag within GTM and then deactivate the UA tag after 7/1/2023 when UA is no longer processing hits (without changes to the website).

**Comment by mattpen** [comment]
> One potential benefit of using GTM that I see: we could activate both the GA4 tag and UA tag within GTM and then deactivate the UA tag after 7/1/2023 when UA is no longer processing hits (without changes to the website).

Yep, I think that would work.

> the capabilities of GTM regarding code-less event tracking.

In the Google Tag Manager admin tool, then only thing I saw was the same events we get automatically with gtag.  It doesn't look highly customizable, just more automatic than before.  

<img width="1000" alt="image" src="https://user-images.githubusercontent.com/11747676/189382597-f22fddcc-3d39-492a-a7a0-d373167a22f6.png">

**Comment by oliver-phet** [comment]
[Here's a quick example](https://www.optimizesmart.com/event-tracking-in-google-tag-manager-v2-complete-guide/#0-how-to-track-google-analytics-events-via-google-tag-manager-) I just found for tracking Download button clicks via a custom event entirely within GTM. This (along with others I've found) seem to be written for UA environments and aren't as relevant now that GA4 collects this type of info by default. But it provides an example of something that we might be able to utilize.

**Comment by oliver-phet** [comment]
Adding some info to this issue:
We've done a text integration of Google Tag Manager (GTM) in both the website and sims. This GTM snippet allows us to fire various tags using various criteria defined via the tag manager. This appears to be working well - the tags are firing when expected and we can see hits to both our GA4 and UA properties.

One issue I'm running into: It has been difficult to verify our UA custom dimensions are being passed correctly. I have configured GTM and UA [matching these instructions](https://support.google.com/tagmanager/answer/6164990?hl=en). Using `https://bayes.colorado.edu/dev/olsonjb/ga6-test.html`, I can see the UA tag firing and data layer in Tag Assistant, but I'm not seeing the page views (with the matching simVersion) in Analytics -- possibly because the data is sampled and only ~46% of page views are shown? 

Here's an example. The page views are recording hits, but it seems none of the custom dimensions are being recorded:
<img width="558" alt="image" src="https://user-images.githubusercontent.com/5090275/194964340-aaeb4ad7-94e4-42e5-8607-f4e9f3721bee.png">
<img width="511" alt="image" src="https://user-images.githubusercontent.com/5090275/194964471-be8d30f3-a1a8-444f-a60e-f63cfacaa183.png">

@mattpen @jonathanolson I'm not sure how to diagnose this. I want to ensure the custom dimensions to our UA properties is saving correctly before switching to GTM, but it doesn't appear to be possible to verify custom dimensions in real time (I'm viewing the page, waiting 24 hours, then checking analytics). Any ideas or thoughts?

**Comment by mattpen** [comment]
It looks like Step 3 for the Data Layer Variable step was missing, which is where it lines the data layer variables up to the custom dimension index.

I added these to the PhET-UA Google Settings Variable:
<img width="752" alt="image" src="https://user-images.githubusercontent.com/11747676/195393579-c4efb43d-cb5f-489d-b4c4-e92a2ef5ace9.png">

I saved these changes but did not deploy them so you can review them first @oliver-phet.

The only thing I was unsure of was that there is a data layer variable of `simLoadType` that doesn't exist in UA and there is a custom dimension (index 5, `simEnvironment`) that doesn't exist in the data layer.  Are these the same thing?

**Comment by oliver-phet** [comment]
I wouldn't think that would matter since the PhET UA tag has the custom dimensions added directly:
![image](https://user-images.githubusercontent.com/5090275/195660182-86e73cb1-a86c-4a22-a5a5-1a0564df7c92.png)

I suppose I could remove the custom dimensions on the Tag and keep them in the Variable, maybe it will work differently?

> The only thing I was unsure of was that there is a data layer variable of simLoadType that doesn't exist in UA and there is a custom dimension (index 5, simEnvironment) that doesn't exist in the data layer. Are these the same thing?

Yes, I verified this separately with JO. Same thing just called Environment in UA.

**Comment by oliver-phet** [comment]
@mattpen I tried the approach you suggested (adding the custom dimensions to the UA variables), but I'm still not getting the dimensions in Analytics.
The pageview hits are coming through, just no custom dimensions :(

Should we meet again to sanity check there isn't something else I missed?

**Comment by mattpen** [comment]
Sure, happy to meet next week. Let's connect on slack

**Comment by oliver-phet** [comment]
This has been resolved and GTM is working well for our internal UA and GA4 accounts!
