### ISSUE TITLE
Adjust Google Analytics storage for EU countries

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/phetcommon#64]
I'll be reverting part of https://github.com/phetsims/phetcommon/commit/08bcc1573d236e0dda716a41c16db20ce46545e7, to restore the behavior we had at https://github.com/phetsims/phetcommon/commit/b88c890371ed204ae273954553baebfd5951e5dc.

**Comment by oliver-phet** [comment]
History found in https://github.com/phetsims/website/issues/1190

**Comment by jonathanolson** [comment]
Commit for MR is https://github.com/phetsims/phetcommon/commit/5852114f46bbe755a02065cb9e4167e06245ff1e.

**Comment by jonathanolson** [comment]
In production, closing.
